# Generated by Django 5.1.5 on 2025-01-19 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('tenant_app', '0002_passcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_wheeler_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('four_wheeler_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('heavy_vehicle_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.client')),
            ],
        ),
    ]
