# Generated by Django 5.1.5 on 2025-01-19 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0003_parkingrates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passcode',
        ),
    ]
