# Generated by Django 5.1.5 on 2025-01-20 06:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0004_delete_passcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipt_no', models.CharField(max_length=100)),
                ('vehicle_no', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('TWO_WHEELER', 'Two Wheeler'), ('FOUR_WHEELER', 'Four Wheeler'), ('HEAVY_VEHICLE', 'Heavy Vehicle')], max_length=100)),
                ('checkin_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_time', models.TimeField(blank=True, null=True)),
                ('checkedin_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checked_in_parkings', to=settings.AUTH_USER_MODEL)),
                ('checkedout_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_out_parkings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
