# Generated by Django 5.1.5 on 2025-01-20 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0005_parkingdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingdetails',
            old_name='recipt_no',
            new_name='recipt_number',
        ),
        migrations.RenameField(
            model_name='parkingdetails',
            old_name='vehicle_no',
            new_name='vehicle_number',
        ),
    ]
