# Generated by Django 5.1.5 on 2025-01-20 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0006_rename_recipt_no_parkingdetails_recipt_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingdetails',
            old_name='recipt_number',
            new_name='receipt_number',
        ),
    ]
