# Generated by Django 5.1.5 on 2025-01-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0007_rename_recipt_number_parkingdetails_receipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingdetails',
            name='receipt_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
