# Generated by Django 5.1.5 on 2025-01-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0008_alter_parkingdetails_receipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingdetails',
            name='total_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
