# Generated by Django 5.1.5 on 2025-01-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0009_alter_parkingdetails_total_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingdetails',
            old_name='receipt_number',
            new_name='receipt_id',
        ),
    ]
