# Generated by Django 5.1.5 on 2025-01-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='passcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='passcode_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
