# Generated by Django 5.1.5 on 2025-01-19 16:40

import django.utils.timezone
import tenant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_client_passcode_client_passcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='passcode',
            field=models.CharField(default=tenant.models.generate_passcode, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='passcode_expires_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
